### ISSUE TITLE
As a user I want to see a list of stores that are close to me

### ISSUE THREAD

**Issue by stayradiated** [stayradiated/clickandcollect.nz#2]
I believe most people who use the site will be interested in the supermarkets nearest them. By using the [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API) and knowing the longitude/latitude of each supermarket, the site can automatically display the supermarkets that are nearby.

**Comment by NPCtom** [comment]
Can I create a pull request for this?

**Comment by stayradiated** [comment]
@NPCtom PR's are very welcome!

I should have updated this issue though -- I've been working on this today, and am just about to publish it.

**Comment by stayradiated** [comment]
Fixed with #15.
